version: 2.0

workflows:
  version: 2
  test:
    jobs:
      - bundle_dependencies-36
      - bundle_dependencies-35
      - mypy_type_check-36:
          requires:
            - bundle_dependencies-35
            - bundle_dependencies-36
      - run_tests-36:
          requires:
            - bundle_dependencies-36
      - run_tests-35:
          requires:
            - bundle_dependencies-35
      - reencryption_memory_profile-36:
          requires:
            - run_tests-35
            - run_tests-36

      - doctests-36:
          requires:
            - run_tests-35
            - run_tests-36

python_35_base: &python_35_base
    working_directory: ~/pyUmbral-35
    docker:
      - image: circleci/python:3.5

python_36_base: &python_36_base
    working_directory: ~/pyUmbral-36
    docker:
      - image: circleci/python:3.6

jobs:
  bundle_dependencies-36:
    <<: *python_36_base
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ checksum "Pipfile" }}-py36
      - run:
          name: Install Python dependencies with Pipenv
          command: pipenv install --three --dev
      - save_cache:
          paths:
            - "~/.local/share/virtualenvs/"
          key: v1-deps-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ checksum "Pipfile" }}-py36

  bundle_dependencies-35:
    <<: *python_35_base
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ checksum "Pipfile" }}-py35
      - run:
          name: Install Python dependencies with Pipenv
          command: pipenv install --three --dev
      - save_cache:
          paths:
            - "~/.local/share/virtualenvs/"
          key: v1-deps-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ checksum "Pipfile" }}-py35

  run_tests-36:
    <<: *python_36_base
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ checksum "Pipfile" }}-py36
      - run:
          name: pyUmbral Tests (Python 3.6)
          command: pipenv run pytest --cov=. --cov-report=html --junitxml=./reports/pytest/python36-results.xml
      - store_test_results:
          path: /reports/pytest
      - store_artifacts:
          path: ./htmlcov

  run_tests-35:
    <<: *python_35_base
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ checksum "Pipfile" }}-py35
      - run:
          name: pyUmbral Tests (Python 3.5)
          command: pipenv run pytest --cov=. --cov-report=html  --junitxml=./reports/pytest/python35-results.xml
      - store_test_results:
          path: /reports/pytest
      - store_artifacts:
          path: ./htmlcov

  reencryption_memory_profile-36:
    <<: *python_36_base
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ checksum "Pipfile" }}-py36
      - run:
          name: Install Profiling Tools
          command: |
              sudo apt-get update
              sudo apt install -y valgrind
              sudo apt install -y massif-visualizer
      - run:
          name: Profile Re-Encryption Memory Usage
          command: |
              pipenv run valgrind --tool=massif --massif-out-file=./reencryption_memory_profile.massif.out python3 ./tests/scripts/reencryption_memory_profile.py 1000
      - store_artifacts:
          path: ./reencryption_memory_profile.massif.out

  mypy_type_check-36:
    <<: *python_36_base
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ checksum "Pipfile" }}-py36
      - run:
          name: Run Mypy Static Type Checks
          command: |
              pipenv install --dev --skip-lock lxml
              pipenv run mypy --xslt-html-report ./mypy_report ./umbral --config-file=mypy.ini
      - store_artifacts:
          path: ./mypy_report

  doctests-36:
    working_directory: ~/pyUmbral-36/
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile" }}-Python36
      - run:
          name: Run Documentation Tests
          command: |
              pipenv install -e . --skip-lock
              cd docs
              pipenv run make doctest
      - store_artifacts:
          path: ./docs/build/doctest/output.txt
